services:

  nginx:
    image: nginx:1.29.1
    restart: always
    ports:
      - 80:80
  
  postgresdb:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes: 
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:5.4.0
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  db-data:
